apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-03-deployment
spec:
  selector:
    matchLabels:
      app: api-03
  replicas: 1    
  template:
    metadata:
      labels:
        app: api-03
    spec:
      containers:
      - name: api-03
        image: fardin31/docker_api_03_image:v1
        ports:
        - containerPort: 80
